# Site settings
title: Hongshen Chen, Ph.D.
#general_email: your_general_email@gmail.com
academic_email: ac#chenhongshen.com (#--->@)

description: > # this means to ignore newlines until "baseurl:"
  Hongshen Chen, Research Scientist with Data Science Lab, JD.com. Currently, I'm focusing on dialogue and interactive system, natural language processing.

#baseurl: "/academic-portfolio" # the subpath of your site, e.g. /blog/

url: "https://chenhongshen.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
#github_username: github_username
#linkedin_username: linkedin_username
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
